# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aed7f903bc98feee43966ffb45213183e198bedd15cc04a02713c5b543fa379b88c8098e28b639ea850c97e5784ba0d5bbe4a82d702256a3c0d2b1435ffde534

test:
  secret_key_base: e37fd689873cc80fc64c8e96b83e3e686b63c3850e96513395e8e233b0c1decdc999cc2c3e5dee67a6be0a51cde4c981d5c5f02dc6e3ddb11be9b76011ff0c1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
